# Generated by Django 5.0.3 on 2024-04-08 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('Compound_id', models.IntegerField(primary_key=True, serialize=False)),
                ('C_Name', models.CharField(max_length=255)),
                ('C_Flavour', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiskey.useradmin')),
            ],
        ),
        migrations.CreateModel(
            name='Whiskey',
            fields=[
                ('Whiskey_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('W_Name', models.CharField(max_length=255)),
                ('W_Maker', models.CharField(max_length=255)),
                ('W_Chemical', models.CharField(max_length=255)),
                ('W_Chemical_Strength', models.IntegerField()),
                ('W_Flavour', models.CharField(max_length=255)),
                ('W_Contact_name', models.CharField(max_length=255)),
                ('W_contact_url', models.URLField()),
                ('Compound_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whiskey.compound')),
            ],
        ),
    ]
